default:
    @just --list

# Refuse to package from any branch other than main.
_assert-main:
    #!/usr/bin/env bash
    set -euo pipefail
    branch=$(git branch --show-current)
    if [ "$branch" != "main" ]; then
        echo "ERROR: packaging can only be run from main (currently on '$branch')" >&2
        exit 1
    fi

# Build locally for development.
build:
    #!/usr/bin/env bash
    set -euo pipefail
    meson setup build --prefix=/usr --reconfigure 2>/dev/null || meson setup build --prefix=/usr
    meson compile -C build

# Build the Arch package in a clean chroot and upload it.
package: _assert-main
    #!/usr/bin/env bash
    set -euo pipefail
    sw1nn-makepkg-chroot -C packaging/arch
    # pkgver is generated by the PKGBUILD pkgver() function, so it is only
    # known after the build has rewritten the PKGBUILD.
    pkgver=$(sed -n 's/^pkgver=//p' packaging/arch/PKGBUILD)
    sw1nn-pkg-ctl upload packaging/arch/*-"$pkgver"-*.pkg.tar.zst
