default:
    @just --list

# Refuse to package from any branch other than main.
_assert-main:
    #!/usr/bin/env bash
    set -euo pipefail
    branch=$(git branch --show-current)
    if [ "$branch" != "main" ]; then
        echo "ERROR: packaging can only be run from main (currently on '$branch')" >&2
        exit 1
    fi

# Build locally for development.
build:
    #!/usr/bin/env bash
    set -euo pipefail
    meson setup build --prefix=/usr --reconfigure 2>/dev/null || meson setup build --prefix=/usr
    meson compile -C build

# Build the Arch package in a clean chroot and upload it.
package: _assert-main
    #!/usr/bin/env bash
    set -euo pipefail
    dir=packaging/arch/sw1nn-lxi-tools-git
    sw1nn-makepkg-chroot -C "$dir"
    # pkgver is generated by the PKGBUILD pkgver() function, so it is only
    # known after the build has rewritten the PKGBUILD.
    pkgver=$(sed -n 's/^pkgver=//p' "$dir"/PKGBUILD)
    sw1nn-pkg-ctl upload "$dir"/*-"$pkgver"-*.pkg.tar.zst

# Build and upload sw1nn-liblxi, which provides the liblxi dependency.
package-liblxi: _assert-main
    #!/usr/bin/env bash
    set -euo pipefail
    # liblxi is AUR-only upstream, so a clean chroot cannot resolve it until
    # this package is in the sw1nn repo. Run this before `just package` on a
    # fresh repo, and whenever the pinned liblxi version changes.
    dir=packaging/arch/sw1nn-liblxi
    sw1nn-makepkg-chroot -C "$dir"
    pkgver=$(sed -n 's/^pkgver=//p' "$dir"/PKGBUILD)
    sw1nn-pkg-ctl upload "$dir"/*-"$pkgver"-*.pkg.tar.zst
